version: "3.9"

services:
    webserver:
        image: nginx:1.19
        hostname: webserver
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites-config:/etc/nginx/conf.d
            - ./nginx/logs:/var/log/nginx
        ports:
            - 80:80
        restart: unless-stopped

    application:
        hostname: application
        build:
            context: .
            dockerfile: ./docker/ApplicationDockerfile
        volumes:
            - ./app:/app
        env_file:
          - ./docker/Application.env
        restart: unless-stopped