version: "3.9"

services:
    webserver:
        image: nginx:1.19
        hostname: webserver
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites-config:/etc/nginx/conf.d
            - ./docker/nginx/logs:/var/log/nginx
        ports:
            - 80:80
        restart: unless-stopped

    application:
        hostname: application
        build:
            context: .
            dockerfile: ./docker/Application/ApplicationDockerfile
        volumes:
            - ./app:/app
        devices:
            - "/dev/video0:/dev/video0"
        env_file:
            - ./docker/Application/Application.env
        restart: unless-stopped

    node:
        image: node:16-alpine3.11
        hostname: node
        volumes:
            - ./app/gui/src:/app/src
            - ./app/gui/static:/app/dist
            - ./package.json:/app/package.json
            - ./webpack.config.js:/app/webpack.config.js
            - ./package-lock.json:/app/package-lock.json
            - ./docker/node/entrypoint.sh:/app/entrypoint.sh
        working_dir: /app
        entrypoint: /app/entrypoint.sh
        restart: unless-stopped